- name: Install HAProxy
  yum:
    name: haproxy
    state: present

- name: Install firewalld if not installed
  package:
    name: firewalld
    state: present

- name: Ensure firewalld is started and enabled
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: Ensure python3-firewall is installed on the control node
  become: true
  package:
    name: python3-firewall
    state: present

- name: Add firewall rules for HAProxy
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - 80/tcp
    - 443/tcp
    - 6443/tcp
    - 22623/tcp
    - 32700/tcp
    - 1936/tcp

- name: Set semanage ports for SELinux
  seport:
    ports: "{{ item.port }}"
    proto: tcp
    setype: http_port_t
    state: present
  loop:
    - { port: 22623 }
    - { port: 6443 }
    - { port: 32700 }
    - { port: 1936 }

- name: Start and enable HAProxy service
  systemd:
    name: haproxy
    state: started
    enabled: true