---
# tasks file for openshift-forwarder
- name: install-haproxy
  include_tasks: install-haproxy.yaml
  #tags: install-haproxy

- name: configure-haproxy
  include_tasks: configure-haproxy.yaml
  #tags: configure-haproxy